language: python
# python versions to use during the tests
python:
    - "3.4"
    - "3.6"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
#    - py.test
    - python3 main.py -sim permutate_only
    - python3 main.py -sim permutate_only --debug
    - python3 main.py -sim permutate_only -i input.txt -o out.simc -l legs/102/103/104/105
    - python3 main.py -sim permutate_only -gems
    - python3 main.py -sim permutate_only --unique_jewelry False
branches:
  only:
   - master
#after_success:
#    - coveralls
notifications:
  email:
#    recipients:
    on_success: change
    on_failure: always